version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  server:
    build: ./server
    container_name: fastapi-server
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - mongo

#  client:
#    build: ./client
#    container_name: nextjs-client
#    ports:
#      - "3000:3000"
#    depends_on:
#      - server

volumes:
  mongo_data:
